// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isqonbvdutojkmjyckmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzcW9uYnZkdXRvamttanlja216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTY4MzAsImV4cCI6MjA2MTI3MjgzMH0.Z4yQqw7uMG1k_EWzPX3nb3_3wOzbBhtXyXBrmGVRpNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);